### PR TITLE
5 crash index

### LINKED ISSUE #5: Client crashes when wrong game index is entered
Server disconnects client when input other than a valid game index is received. Instead, client should be notified they've entered an invalid index and be prompted again.

### LINKED ISSUE #6: Client crashes when wrong pit number is entered
Server disconnects client when an invalid pit number is entered for a move. Instead, the client should be notified that they've entered an invalid move and be prompted again.

### PR DESCRIPTION
**Pull request by loganballard**
fixes #6 

Also fixes the fact that the turns were backwards lol see client_input_handler.rs::221

### CODE REVIEW

File: src/client_input_handler.rs [hunk 1]
```diff
@@ -240,24 +238,67 @@ fn get_current_gamestate() -> Msg {
...
+            end: BOARD_LENGTH,
+        }
+    };
+    if range_of_valid_moves.contains(&move_to_make) && game_state.game_board[move_to_make] != 0 {
+        return true;
+    }
+    if !range_of_valid_moves.contains(&move_to_make) {
+        println!(
+            "Move was not in the playable range of moves, which is {:?} for you.",
+            &range_of_valid_moves
```
Comment (rooneyshuman) [inline src/client_input_handler.rs]: This range is incorrect. Player1 should be able to move slots 1-6 but the message gives the range `1..7` and player2 should be 8-13 but error says `8..14`

Comment (loganballard) [reply src/client_input_handler.rs]: ah yes, the range object is [start, end) so the end is not actually included...

Comment (loganballard) [reply src/client_input_handler.rs]: updated
